# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, ... }:
{
  flake.modules.nixos.henri-atixnet-laptop = {
    boot.initrd.availableKernelModules = [
      "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sr_mod"
    ];

    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    boot.loader.efi.efiSysMountPoint = "/boot/efi";

    # added by me
    networking.useDHCP = lib.mkDefault true;
    powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  };
}
